// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	OpenId   string `josn:"open_id"`
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Email    string `json:"email"`
	Role     int64  `json:"role"`
	Avatar   string `json:"avatar"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	UserName string `json:"username"`
	Sex      int64  `json:"sex"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type WXMiniAuthReq struct {
	Code          string `json:"code"`
	IV            string `json:"iv"`
	EncryptedData string `json:"encryptedData"`
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type OrderChangeInfo struct {
	CreateTime int64 `json:"createTime"` // 变动身份时间
	OperatorId int64 `json:"operatorId"` // 操作人
	NewRole    int64 `json:"newRole"`    // 新身份 '身份 0-申请队员 1-岗前培训 2-见习队员 3-正式队员 4-督导老师 5-区域负责人 6-组委会 7-主任'
	OldRole    int64 `json:"oldRole"`    // 旧身份
}

type RoleChangeInfoListReq struct {
	UserId int64 `json:"userId"`
}

type RoleChangeInfoListResp struct {
	List []OrderChangeInfo `json:"list"`
}

type ChangeRoleReq struct {
	UserId  int64 `json:"userId"`
	NewRole int64 `json:"newRole"`
}

type ChangeRoleResp struct {
	CreateTime int64 `json:"createTime"` // 变动身份时间
	NewRole    int64 `json:"newRole"`    // 新身份 '身份 0-申请队员 1-岗前培训 2-见习队员 3-正式队员 4-督导老师 5-区域负责人 6-组委会 7-主任'
	OldRole    int64 `json:"oldRole"`    // 旧身份
}
