// Code generated by goctl. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	objectiveExamFieldNames          = builder.RawFieldNames(&ObjectiveExam{})
	objectiveExamRows                = strings.Join(objectiveExamFieldNames, ",")
	objectiveExamRowsExpectAutoSet   = strings.Join(stringx.Remove(objectiveExamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	objectiveExamRowsWithPlaceHolder = strings.Join(stringx.Remove(objectiveExamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	objectiveExamModel interface {
		Insert(ctx context.Context, data *ObjectiveExam) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ObjectiveExam, error)
		FindOneByUserIdTime(ctx context.Context, userId int64, time string) (*ObjectiveExam, error)
		Update(ctx context.Context, data *ObjectiveExam) error
		Delete(ctx context.Context, id int64) error
	}

	defaultObjectiveExamModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ObjectiveExam struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		UserId     int64     `db:"user_id"`
		Result     int64     `db:"result"` // 结果 0:不合格 1:合格
		Time       string    `db:"time"`   // 考试日期
	}
)

func newObjectiveExamModel(conn sqlx.SqlConn) *defaultObjectiveExamModel {
	return &defaultObjectiveExamModel{
		conn:  conn,
		table: "`objective_exam`",
	}
}

func (m *defaultObjectiveExamModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultObjectiveExamModel) FindOne(ctx context.Context, id int64) (*ObjectiveExam, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", objectiveExamRows, m.table)
	var resp ObjectiveExam
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultObjectiveExamModel) FindOneByUserIdTime(ctx context.Context, userId int64, time string) (*ObjectiveExam, error) {
	var resp ObjectiveExam
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `time` = ? limit 1", objectiveExamRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, time)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultObjectiveExamModel) Insert(ctx context.Context, data *ObjectiveExam) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, objectiveExamRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.UserId, data.Result, data.Time)
	return ret, err
}

func (m *defaultObjectiveExamModel) Update(ctx context.Context, newData *ObjectiveExam) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, objectiveExamRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.UserId, newData.Result, newData.Time, newData.Id)
	return err
}

func (m *defaultObjectiveExamModel) tableName() string {
	return m.table
}
