// Code generated by goctl. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	pendingPersonnelFieldNames          = builder.RawFieldNames(&PendingPersonnel{})
	pendingPersonnelRows                = strings.Join(pendingPersonnelFieldNames, ",")
	pendingPersonnelRowsExpectAutoSet   = strings.Join(stringx.Remove(pendingPersonnelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	pendingPersonnelRowsWithPlaceHolder = strings.Join(stringx.Remove(pendingPersonnelFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	pendingPersonnelModel interface {
		Insert(ctx context.Context, data *PendingPersonnel) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PendingPersonnel, error)
		FindOneByUserId(ctx context.Context, userId int64) (*PendingPersonnel, error)
		Update(ctx context.Context, data *PendingPersonnel) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPendingPersonnelModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PendingPersonnel struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		UserId     int64     `db:"user_id"`    // 待处理人员id
		Reason     string    `db:"reason"`     // 原因
		OperateId  int64     `db:"operate_id"` // 操作人id
	}
)

func newPendingPersonnelModel(conn sqlx.SqlConn) *defaultPendingPersonnelModel {
	return &defaultPendingPersonnelModel{
		conn:  conn,
		table: "`pending_personnel`",
	}
}

func (m *defaultPendingPersonnelModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPendingPersonnelModel) FindOne(ctx context.Context, id int64) (*PendingPersonnel, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", pendingPersonnelRows, m.table)
	var resp PendingPersonnel
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPendingPersonnelModel) FindOneByUserId(ctx context.Context, userId int64) (*PendingPersonnel, error) {
	var resp PendingPersonnel
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", pendingPersonnelRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPendingPersonnelModel) Insert(ctx context.Context, data *PendingPersonnel) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, pendingPersonnelRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.UserId, data.Reason, data.OperateId)
	return ret, err
}

func (m *defaultPendingPersonnelModel) Update(ctx context.Context, newData *PendingPersonnel) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, pendingPersonnelRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.UserId, newData.Reason, newData.OperateId, newData.Id)
	return err
}

func (m *defaultPendingPersonnelModel) tableName() string {
	return m.table
}
