// Code generated by goctl. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subjectiveExamFieldNames          = builder.RawFieldNames(&SubjectiveExam{})
	subjectiveExamRows                = strings.Join(subjectiveExamFieldNames, ",")
	subjectiveExamRowsExpectAutoSet   = strings.Join(stringx.Remove(subjectiveExamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	subjectiveExamRowsWithPlaceHolder = strings.Join(stringx.Remove(subjectiveExamFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	subjectiveExamModel interface {
		Insert(ctx context.Context, data *SubjectiveExam) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SubjectiveExam, error)
		FindOneByUserIdTime(ctx context.Context, userId int64, time string) (*SubjectiveExam, error)
		Update(ctx context.Context, data *SubjectiveExam) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSubjectiveExamModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SubjectiveExam struct {
		Id         int64     `db:"id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		DeleteTime time.Time `db:"delete_time"`
		DelState   int64     `db:"del_state"`
		UserId     int64     `db:"user_id"`
		Result     int64     `db:"result"` // 结果 0:不合格 1:合格
		Time       string    `db:"time"`   // 考试日期
	}
)

func newSubjectiveExamModel(conn sqlx.SqlConn) *defaultSubjectiveExamModel {
	return &defaultSubjectiveExamModel{
		conn:  conn,
		table: "`subjective_exam`",
	}
}

func (m *defaultSubjectiveExamModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSubjectiveExamModel) FindOne(ctx context.Context, id int64) (*SubjectiveExam, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", subjectiveExamRows, m.table)
	var resp SubjectiveExam
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubjectiveExamModel) FindOneByUserIdTime(ctx context.Context, userId int64, time string) (*SubjectiveExam, error) {
	var resp SubjectiveExam
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `time` = ? limit 1", subjectiveExamRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, time)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubjectiveExamModel) Insert(ctx context.Context, data *SubjectiveExam) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, subjectiveExamRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.UserId, data.Result, data.Time)
	return ret, err
}

func (m *defaultSubjectiveExamModel) Update(ctx context.Context, newData *SubjectiveExam) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, subjectiveExamRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.UserId, newData.Result, newData.Time, newData.Id)
	return err
}

func (m *defaultSubjectiveExamModel) tableName() string {
	return m.table
}
