// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Email    string `json:"email"`
	Role     int64  `json:"role"`
	Avatar   string `json:"avatar"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type WaterMark struct {
	Timestamp int64  `json:"timestamp"`
	AppID     string `json:"appid"`
}

type PhoneInfo struct {
	PhoneNumber     string    `json:"phone_number"`      // 用户绑定的手机号
	PurePhoneNumber string    `json:"pure_phone_number"` // 没有区号的手机号
	CountryCode     string    `json:"country_code"`      // 区号
	WaterMark       WaterMark `json:"watermark"`         // 数据水印
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
	Role         int64  `json:"role"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
	Role         int64  `json:"role"`
}

type WXMiniAuthReq struct {
	Code        string `json:"code"`
	PhoneNumber string `json:"phone_number"`
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
	Role         int64  `json:"role"`
}

type GetPhoneNumberReq struct {
	Code string `json:"code"` // getPhoneNumber(前端调用的函数)返回的code与wx.login返回的code作用不一样
}

type GetPhoneNumberResp struct {
	PhoneInfo PhoneInfo `json:"phone_info"`
}

type UserInfoResp struct {
	UserInfo User `json:"user_info"`
}

type GetUserInfoReq struct {
	UserId int64 `json:"user_id"`
}

type GetAllUserInfoReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetAllUserInfoResp struct {
	List []User `json:"list"`
}

type UploadAvatarResp struct {
	Url string `json:"url"`
}

type ImportExcelResp struct {
	List []User `json:"list"`
}

type EditUserInfoReq struct {
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type GetAccessTokenResp struct {
	AccessToken string `json:"access_token"`
}

type GetAllUserInfoByRoleReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
	Role     int64 `json:"role"`
}

type GetAllUserInfoByRoleResp struct {
	List []User `json:"list"`
}

type GetTrainingUserInfoByMobileReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"page_size"`
	Mobile   string `json:"mobile"`
}

type GetTrainingUserInfoByMobileResp struct {
	UserInfo User `json:"user_info"`
}

type RescueDurationResp struct {
	RescueDuration string `json:"rescue_duration"`
}

type RescueFrequencyResp struct {
	RescueFrequency int64 `json:"rescue_frequency"`
}

type GetUserRescueDurationReq struct {
	UserId int64 `json:"user_id"`
}

type GetUserRescueDurationResp struct {
	RescueDuration string `json:"rescue_duration"`
}

type GetUserRescueFrequencyReq struct {
	UserId int64 `json:"user_id"`
}

type GetUserRescueFrequencyResp struct {
	RescueFrequency int64 `json:"rescue_frequency"`
}

type RoleChangeInfo struct {
	Id         int64  `json:"id"`
	CreateTime string `json:"create_time"` // 变动身份时间
	UserId     int64  `json:"user_id"`     // 身份变动用户Id
	OperatorId int64  `json:"operator_id"` // 操作人Id
	NewRole    int64  `json:"new_role"`    // 新身份 '0-申请队员 1-岗前培训 2-见习队员 3-正式队员 4-督导老师 30-普通队员 31-核心队员 32-区域负责人 33-组委会成员 34-组委会主任'
	OldRole    int64  `json:"old_role"`    // 旧身份
}

type RoleChangeInfoListReq struct {
	UserId int64 `json:"user_id"`
}

type RoleChangeInfoListResp struct {
	List []RoleChangeInfo `json:"list"`
}

type ChangeRoleReq struct {
	UserId  int64 `json:"user_id"`
	NewRole int64 `json:"new_role"`
}

type RescueTarget struct {
	Id                 int64  `json:"id"` // 救援对象id
	CreateTime         string `json:"create_time"`
	UpdateTime         string `json:"update_time"`
	WeiboAddress       string `json:"weibo_address"`        // 救援对象微博地址（唯一标识）
	Nickname           string `json:"nickname"`             // 救援对象昵称（按最新的救援信息数据）
	Status             int64  `json:"status"`               // 救援状态（0-待救援 1-救援中 2-已救援）
	StartTime          string `json:"start_time"`           // 救援起始时间
	EndTime            string `json:"end_time"`             // 救援结束时间
	RescueTeacher1Id   int64  `json:"rescue_teacher1_id"`   // 救援老师1id
	RescueTeacher1Name string `json:"rescue_teacher1_name"` // 救援老师1姓名
	RescueTeacher1Role int64  `json:"rescue_teacher1_role"` // 救援老师1身份
	RescueTeacher2Id   int64  `json:"rescue_teacher2_id"`   // 救援老师2id
	RescueTeacher2Name string `json:"rescue_teacher2_name"` // 救援老师2姓名
	RescueTeacher2Role int64  `json:"rescue_teacher2_role"` // 救援老师2身份
	RescueTeacher3Id   int64  `json:"rescue_teacher3_id"`   // 救援老师3id
	RescueTeacher3Name string `json:"rescue_teacher3_name"` // 救援老师3姓名
	RescueTeacher3Role int64  `json:"rescue_teacher3_role"` // 救援老师3身份
	Description        string `json:"description"`          // 救援过程描述
	Evaluation         string `json:"evalutaion"`           // 最终评价
}

type RescueInfo struct {
	Id                int64  `json:"id"`
	CreateTime        string `json:"create_time"` // 救援信息在数据库中的创建时间，相当于管理员导入的时间
	UpdateTime        string `json:"update_time"`
	RescueTargetId    int64  `json:"rescue_target_id"` // 本条救援信息所属救援对象的id
	ReleaseTime       string `json:"release_time"`     // 此条微博的发布时间
	WeiboAccount      string `json:"weibo_account"`
	WeiboAddress      string `json:"weibo_address"`
	Nickname          string `json:"nickname"`
	RiskLevel         string `json:"risk_level"`
	Area              string `json:"area"`
	Sex               int64  `json:"sex"`
	Birthday          string `json:"birthday"`
	BriefIntroduction string `json:"brief_introduction"`
	Text              string `json:"text"`
}

type RescueProcess struct {
	Id              int64  `json:"id"`
	CreateTime      string `json:"create_time"`
	UpdateTime      string `json:"update_time"`
	RescueTeacherId int64  `json:"rescue_teacher_id"`
	RescueInfoId    int64  `json:"rescue_info_id"`
	StartTime       string `json:"start_time"` // 本次救援起始时间
	EndTime         string `json:"end_time"`   // 本次救援结束时间
	Duration        string `json:"duration"`   // 时长（系统计算）
	Evaluation      string `json:"evaluation"` // 评价
}

type Signature struct {
	Id                int64  `json:"id"`
	CreateTime        string `json:"create_time"`
	UpdateTime        string `json:"update_time"`
	RescueTeacherId   int64  `json:"rescue_teacher_id"`
	RescueTeacherName string `json:"rescue_teacher_name"`
	RescueTeacherRole int64  `json:"rescue_teacher_role"`
	RescueTargetId    int64  `json:"rescue_target_id"`
	Image             string `json:"image"`
}

type Area struct {
	Name            string `json:"name"`             // 省份名称
	RescueFrequency int64  `json:"rescue_frequency"` // 救援次数
}

type AreaRescueFrequencyResp struct {
	List []Area `json:"list"`
}

type Year struct {
	Name            string `json:"name"`             // 年份
	RescueFrequency int64  `json:"rescue_frequency"` // 救援次数
}

type YearRescueFrequencyResp struct {
	List []Year `json:"list"`
}

type ReleaseRescueInfoReq struct {
	ReleaseTime       string `json:"release_time"`       // 此条微博的发布时间
	WeiboAccount      string `json:"weibo_account"`      // 微博账户
	WeiboAddress      string `json:"weibo_address"`      // 微博地址
	Nickname          string `json:"nickname"`           // 昵称
	RiskLevel         string `json:"risk_level"`         // 危险级别
	Area              string `json:"area"`               // 所在城市
	Sex               int64  `json:"sex"`                // 性别
	Birthday          string `json:"birthday"`           // 生日
	BriefIntroduction string `json:"brief_introduction"` // 简介
	Text              string `json:"text"`               // 信息原文
	Flag              int64  `json:"flag"`               // 是否发布订阅消息
}

type AuthReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type AuthResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type RescueInfosReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type RescueInfosResp struct {
	List []RescueInfo `json:"list"`
}

type GetRescueInfoByAddressReq struct {
	Address  string `json:"address"`
	Page     int64  `json:"page"`
	PageSize int64  `json:"page_size"`
}

type GetRescueInfoByRescueTargetIdReq struct {
	RescueTargetId int64 `json:"rescue_target_id"`
	Page           int64 `json:"page"`
	PageSize       int64 `json:"page_size"`
}

type GetRescueInfoByRescueTargetIdResp struct {
	List []RescueInfo `json:"list"`
}

type GetRescueInfoByRescueTeacherNameReq struct {
	RescueTeacherName string `json:"rescue_teacher_name"`
	Page              int64  `json:"page"`
	PageSize          int64  `json:"page_size"`
}

type GetRescueInfoByRescueTeacherNameResp struct {
	List []RescueInfo `json:"list"`
}

type ClaimRescueTargetReq struct {
	RescueTargetId int64 `json:"rescue_target_id"`
}

type GetRescueTaskReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetRescueTaskResp struct {
	List []RescueTarget `json:"list"`
}

type GetRescueTargetInfoReq struct {
	RescueTargetId int64 `json:"rescue_target_id"`
}

type GetRescueTargetInfoResp struct {
	RescueTargetInfo RescueTarget `json:"rescue_target_info"`
}

type SignReq struct {
	RescueTargetId int64  `json:"rescue_target_id"`
	Image          string `json:"image"`
}

type GetSignatureReq struct {
	RescueTargetId int64 `json:"rescue_target_id"`
}

type GetSignatureResp struct {
	List []Signature `json:"list"`
}

type RescueProcessReq struct {
	RescueInfoId int64  `json:"rescue_info_id"`
	StartTime    string `json:"start_time"`
	EndTime      string `json:"end_time"`
	Evaluation   string `json:"evaluation"`
}

type GetRescueProcessReq struct {
	RescueInfoId int64 `json:"rescue_info_id"`
	Page         int64 `json:"page"`
	PageSize     int64 `json:"page_size"`
}

type GetRescueProcessResp struct {
	List []RescueProcess `json:"list"`
}

type SetRescueDurationThresholdReq struct {
	Threshold int64 `json:"threshold"`
}

type ApplicationForm struct {
	Id                    int64  `json:"id"`
	CreateTime            string `json:"create_time"`
	UpdateTime            string `json:"update_time"`
	UserId                int64  `json:"user_id"`
	Mobile                string `json:"mobile"`
	Username              string `json:"username"`
	Sex                   int64  `json:"sex"`
	Email                 string `json:"email"`
	Address               string `json:"address"`
	Birthday              string `json:"birthday"`
	Status                int64  `json:"status"`
	RegionalHeadId        int64  `json:"regional_head_id"`
	OrganizingCommitteeId int64  `json:"organizing_committee_id"`
	SubmissionTime        int64  `json:"submission_time"`
}

type FormResp struct {
	Form ApplicationForm `json:"application_form"`
}

type FormsReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type FormsResp struct {
	List []ApplicationForm `json:"list"`
}

type GetByAddressReq struct {
	Address  string `json:"address"`
	Page     int64  `json:"page"`
	PageSize int64  `json:"page_size"`
}

type ProcessReq struct {
	ApplicationFormId int64 `json:"application_form_id"`
	Result            int64 `json:"result"` // 审批结果 0-未通过 1-通过
}

type ProcessWithSubscribeReq struct {
	ApplicationFormId int64  `json:"application_form_id"`
	Result            int64  `json:"result"` // 审批结果 0-未通过 1-通过
	AccessToken       string `json:"access_token"`
}

type GetByStatusReq struct {
	Status   int64 `json:"status"`
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetByStatusResp struct {
	List []ApplicationForm `json:"list"`
}

type EditReq struct {
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
	Email    string `json:"email"`
}

type Exam struct {
	Id     int64  `json:"id"`
	UserId int64  `json:"user_id"`
	Result int64  `json:"result"`
	Time   string `json:"time"`
}

type Grades struct {
	Id     int64  `json:"id"`
	UserId int64  `json:"user_id"`
	Result int64  `json:"result"`
	Time   string `json:"time"`
	Type   string `json:"type"`
}

type EnterGradeReq struct {
	UserId int64  `json:"user_id"`
	Result int64  `json:"result"`
	Time   string `json:"time"`
}

type GetGradesResp struct {
	List []Grades `json:"list"`
}

type File struct {
	Id         int64  `json:"id"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
	FileName   string `json:"file_name"`
	FolderId   int64  `json:"folder_id"`
	Url        string `json:"url"`
}

type Folder struct {
	Id         int64  `json:"id"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
	FolderName string `json:"folder_name"`
	Role       int64  `json:"role"`
}

type ViewingRecord struct {
	Id         int64  `json:"id"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
	UserId     int64  `json:"user_id"`
	Username   string `json:"username"`
	FileId     int64  `json:"file_id"`
	FileName   string `json:"file_name"`
	Duration   int64  `json:"duration"` // 观看时间（多次观看取最大值）
}

type UploadVideoUrlReq struct {
	Url      string `json:"url"`
	FileName string `json:"file_name"`
	FolderId int64  `json:"folder_id"`
}

type UploadVideoResp struct {
	VideoId int64  `json:"video_id"`
	Url     string `json:"url"`
}

type AddFolderReq struct {
	FolderName string `json:"folder_name"`
	Role       int64  `json:"role"`
}

type GetFolderReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetFolderResp struct {
	List []Folder `json:"folder"`
}

type GetVideoReq struct {
	FolderId int64 `json:"folder_id"`
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetVideoResp struct {
	List []File `json:"list"`
}

type EditFolderReq struct {
	FolderId   int64  `json:"folder_id"`
	FolderName string `json:"folder_name"`
	Role       int64  `json:"role"`
}

type EditVideoReq struct {
	VideoId  int64  `json:"video_id"`
	FileName string `json:"file_name"`
	FolderId int64  `json:"folder_id"`
}

type SubmitViewingRecordReq struct {
	FileId   int64 `json:"file_id"`
	Duration int64 `json:"duration"`
}

type GetViewingRecordReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetViewingRecordResp struct {
	List []ViewingRecord `json:"viewing_record"`
}

type GetQiNiuTokenResp struct {
	Token string `json:"token"`
}

type DeleteFolderReq struct {
	FolderId int64 `json:"folder_id"`
}

type DeleteFileReq struct {
	FileId int64 `json:"file_id"`
}
